global:
 scrape_interval:     5s
 evaluation_interval: 5s

scrape_configs:
 - job_name: mysql
   target_groups:
     - targets: [':NODE_IP:9104']
       labels:
         alias: db1

 - job_name: linux
   target_groups:
     - targets: [':NODE_IP:9100']
       labels:
         alias: db1
