global:
  scrape_interval:     1s
  scrape_timeout:      1s
  evaluation_interval: 5s

scrape_configs:
  - job_name: mysql_hr
    scrape_interval:    1s
    scrape_timeout:     1s
    target_groups:
      - targets: ['MYSQL_IP:9101']
        labels:
          alias: db1

  - job_name: mysql_mr
    scrape_interval:    5s
    scrape_timeout:     1s
    target_groups:
      - targets: ['MYSQL_IP:9102']
        labels:
          alias: db1

  - job_name: mysql_lr
    scrape_interval:    60s
    scrape_timeout:     5s
    target_groups:
      - targets: ['MYSQL_IP:9103']
        labels:
          alias: db1

  - job_name: linux
    target_groups:
      - targets: ['MYSQL_IP:9100']
        labels:
          alias: db1

  - job_name: prometheus
    target_groups:
      - targets: ['localhost:9090']
        labels:
          alias: monitor

